### ISSUE TITLE
 [E] Failed to load mod file config/mods/DiscordPlugin.jar. Skipping.

### ISSUE THREAD

**Issue by Volas171** [J-VdS/DiscordPlugin#7]
![image](https://user-images.githubusercontent.com/60143910/125208081-14440900-e256-11eb-8ec8-896aa791e122.png)
config.json file was made but seems like it fails to load it because is trying to load config/home/path/to/the/thing and that's a nonexistent path

**Comment by MaxSMoke-KillSZ-Official** [comment]
I have a same error

**Comment by Volas171** [comment]
managed to fix the config.json error, now its giving another 
![image](https://user-images.githubusercontent.com/60143910/127876055-13f149b3-045f-4926-b975-6bdb4ca5ee8e.png)

**Comment by j-vds** [comment]
Ow srr but couldn't test it becausr Anuke migrated to a new version of gradle.

**Comment by j-vds** [comment]
I will look into it when I have time.

**Comment by j-vds** [comment]
I am working to fix and test it now, I got intelliJ fixed :)

**Comment by j-vds** [comment]
https://discord.gg/5Axd4uAR
Join the testing channel. You could always ask questions there. The plugin can connect etc...

**Comment by j-vds** [comment]
@Volas171 @MaxSMoke-KillSZ-Official new version can be found [here](https://github.com/J-VdS/DiscordPlugin/releases/tag/1.130).

Contact me if it still crashes...

**Comment by Volas171** [comment]
thank you, it’s working now
