### ISSUE TITLE
140+

### ISSUE THREAD

**Issue by MaxSMokeSkaarj** [J-VdS/DiscordPlugin#8]
latest plugin doesnt work with latest release(140.4) build
![Screenshot_20221124_235343](https://user-images.githubusercontent.com/62266921/203801361-1b0e1b02-879c-40ac-ae82-cee344e4e530.png)

**Comment by MaxSMokeSkaarj** [comment]
oh, wait, it may be my fault
p.s sorry. Thats by fault, i forgor change a token

**Comment by VozdyxDev** [comment]
lmao

**Comment by MaxSMokeSkaarj** [comment]
> lmao

у меня 10 серверов, и 10 было в6 до того как релизнулся в7, Я в них запутался :)
I have 10 servers, and 10 were in v6 before the release turned into v7, I got confused in them :)
